# Generated by Django 3.2.7 on 2021-09-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_host', models.CharField(max_length=30)),
                ('classification', models.FloatField(blank=True, null=True)),
                ('host_addresses', models.CharField(max_length=200)),
            ],
        ),
    ]
