# Generated by Django 3.2.7 on 2021-09-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=30)),
                ('guests', models.IntegerField(null=True)),
                ('telephone', models.IntegerField(null=True)),
                ('id_reserve', models.CharField(max_length=10)),
                ('id_airbnb', models.CharField(default='xxxxxxx', max_length=6)),
                ('address_reserve', models.CharField(max_length=100)),
                ('daily', models.IntegerField()),
                ('checkin_day', models.DateField()),
                ('checkin_hour', models.TimeField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('pet', models.CharField(choices=[[('yes', 'yes'), ('no', 'no')]], default='no', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.DateField()),
                ('name_client', models.CharField(max_length=30)),
                ('address_reserve', models.CharField(max_length=100)),
                ('checkout_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.IntegerField()),
                ('id_cleaning', models.CharField(max_length=30)),
                ('hour_cleaning', models.TimeField()),
            ],
        ),
    ]
