# Generated by Django 3.2.7 on 2021-09-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_checkin_checkout_cleaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
